name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build React app
        run: |
          cd Client  # Assuming your React app is in the "Client" directory
          npm install
          npm run build
          echo '/*  /index.html 200' > dist/_redirects  # Updated path to "dist" directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REPOSITORY_TOKEN }}
          publish_dir: Client/dist  # Updated path to "dist" directory

    outputs:
      deployment-url: ${{ steps.deployment.outputs.page_url }}
