name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build React app
        working-directory: Client
        run: |
          npm install
          npm run build
          echo '/*  /index.html 200' > build/_redirects

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REPOSITORY_TOKEN }}
          publish_dir: Client/build  # Change to the correct build directory

    outputs:
      deployment-url: ${{ steps.deployment.outputs.page_url }}
