name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Vite app
        working-directory: Client
        run: |
          npm install
          npm run build
          echo '/*  /index.html 200' > dist/_redirects

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REPOSITORY_TOKEN }}
          publish_dir: Client/dist
